name: equibind
channels:
  - rdkit
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - biopandas=0.4.1
  - biopython=1.79
  - cudatoolkit=11.3.1
  - dgl-cuda11.3=0.9.1
  - icecream=2.1.3
  - joblib=1.1.0
  - matplotlib=3.5.3
  - openbabel=3.1.1
  - pot=0.8.0
  - python=3.7.15
  - pytorch=1.10.0
  - pyyaml=6.0
  - rdkit=2020.09.1.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tensorboard=2.10.0
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - pip:
    - vina==1.2.3

